# Generated by Django 4.0.5 on 2022-06-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo_departamento',
            field=models.IntegerField(verbose_name='costo departamento'),
        ),
    ]
