# Generated by Django 4.0.5 on 2022-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_departamento_costo_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
    ]
